server {
    listen 80;
    server_name ui.logicandlaunch.me;

    location = /health {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        root  /usr/share/nginx/html/ui;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}

server {
    listen 80;
    server_name availity.logicandlaunch.me;

    location = /health {
        add_header Content-Type text/plain;
        return 200 'ok';
    }

    location / {
        root  /usr/share/nginx/html/availity;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}